version: '3.9'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}  # from .env file
    volumes:
      - .:/app
